
<!--[if lte IE 7 ]><html lang="pl-PL" class="ie ie7"><![endif]-->
<!--[if IE 8 ]><html lang="pl-PL" class="ie ie8"><![endif]-->
<!--[if !IE]>--><html lang="pl-PL"><!--<![endif]-->
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title><?= $title ?></title>
    <link href="<?= $base_url ?>/styles/bootstrap/bootstrap.min.css" rel="stylesheet">
    <link href="<?= $base_url ?>/styles/styles.css" rel="stylesheet">
</head>