<div class="col-md-6 col-md-offset-3">
    <div class="page-header">
        <h1>Dodawanie użytkownika</h1>
    </div>

    <form action="/user/add" class="form-horizontal" method="post">
        <div class="form-group">
            <label for="user_login" class="col-sm-2 control-label">Login:</label>
            <div class="col-sm-4">
                <input type="text" class="form-control" id="user_login" name="user_login" placeholder="login"></input>
            </div>
        </div>

        <div class="form-group">
            <label for="user_password" class="col-sm-2 control-label">Hasło:</label>
            <div class="col-sm-4">
                <input type="password" class="form-control" id="user_password" name="user_password" placeholder="hasło"></input>
            </div>
        </div>

        <button type="submit" class="btn btn-success">Dodaj</button>
        <a href="/user/admin" class="btn btn-danger">Anuluj</a>
    </form>
</div>