<!DOCTYPE html>
<html>
    <?php require_once APPLICATION_PATH . '/views/scripts/header.phtml' ?>
    <body>
        <nav class="navbar navbar-default" role="navigation">
            <div class="container-fluid">
                <div class="navbar-header">
                    <a class="navbar-brand" href="/index/landingPage">Szkolenia</a>
                </div>
          </div>
        </nav>
        <div class="container">
            <div class="col-md-6 col-md-offset-3">
                <div class="page-header">
                    <h1><small><i class="glyphicon glyphicon-exclamation-sign red"></i></small> Wystąpił błąd: </h1>
                </div>

                <div class="alert alert-danger" role="alert">
                    <?= $content; ?>
                </div>
                <div class="alert alert-info" role="alert">
                    Skontaktuj sie z <a href="mailto:rutkowski.pl@gmail.com">administratorem</a> systemu 
                </div>
            </div>
        </div>
        <?php require_once APPLICATION_PATH . '/views/scripts/footer.phtml' ?>

        <script src="http://code.jquery.com/jquery.js"></script>
        <script src="<?= $base_url ?>scripts/libs/bootstrap.min.js"></script>
    </body>
</html>